name: e2e

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      # Execute Cypress com Mochawesome (usa seus scripts e gera JSON/HTML)
      - name: Run Cypress (Mochawesome)
        run: npm run test
        # se você quer apenas chrome:
        # run: npm run clean:reports && npx cypress run --browser chrome --reporter mochawesome --reporter-options reportDir=cypress/reports,overwrite=false,html=false,json=true && npm run report:merge && npm run report:gen

      # Mesmo se o teste falhar, suba os artefatos para análise
      - name: Upload Mochawesome HTML
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-html
          path: cypress/reports/html
          if-no-files-found: error

      - name: Upload videos
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore

      - name: Upload screenshots
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore
